const { prefixKeys } = require("../utils")

// https://github.com/sindresorhus/eslint-plugin-unicorn#rules

module.exports = prefixKeys("unicorn/", {
  "better-regex": "warn",
  "catch-error-name": "warn",
  "consistent-destructuring": "off",
  "consistent-function-scoping": "warn",
  "custom-error-definition": "warn",
  "empty-brace-spaces": "warn",
  "error-message": "warn",
  "escape-case": "warn",
  "expiring-todo-comments": "warn",
  "explicit-length-check": "warn",
  "filename-case": "off",
  "import-index": "warn",
  "import-style": "off",
  "new-for-builtins": "warn",
  "no-abusive-eslint-disable": "warn",
  "no-array-callback-reference": "off",
  "no-array-for-each": "off",
  "no-array-push-push": "warn",
  "no-array-reduce": "off",
  "no-console-spaces": "warn",
  "no-for-loop": "warn",
  "no-hex-escape": "warn",
  "no-instanceof-array": "error",
  "no-keyword-prefix": "warn",
  "no-lonely-if": "off",
  "no-nested-ternary": "warn",
  "no-new-array": "error",
  "no-new-buffer": "error",
  "no-null": "off",
  "no-object-as-default-parameter": "warn",
  "no-process-exit": "off",
  "no-this-assignment": "off",
  "no-unreadable-array-destructuring": "off",
  "no-unsafe-regex": "error",
  "no-unused-properties": "off",
  "no-useless-undefined": "warn",
  "no-zero-fractions": "warn",
  "number-literal-case": "warn",
  "numeric-separators-style": "off",
  "prefer-add-event-listener": "error",
  "prefer-array-find": "warn",
  "prefer-array-flat-map": "warn",
  "prefer-array-index-of": "warn",
  "prefer-array-some": "warn",
  "prefer-date-now": "warn",
  "prefer-default-parameters": "warn",
  "prefer-dom-node-append": "warn",
  "prefer-dom-node-dataset": "warn",
  "prefer-dom-node-remove": "warn",
  "prefer-dom-node-text-content": "error",
  "prefer-includes": "warn",
  "prefer-keyboard-event-key": "error",
  "prefer-math-trunc": "error",
  "prefer-modern-dom-apis": "warn",
  "prefer-negative-index": "warn",
  "prefer-number-properties": "error",
  "prefer-optional-catch-binding": "warn",
  "prefer-query-selector": "warn",
  "prefer-reflect-apply": "warn",
  "prefer-regexp-test": "warn",
  "prefer-set-has": "warn",
  "prefer-spread": "warn",
  "prefer-string-replace-all": "warn",
  "prefer-string-slice": "error",
  "prefer-string-starts-ends-with": "warn",
  "prefer-string-trim-start-end": "error",
  "prefer-ternary": "off",
  "prefer-type-error": "warn",
  "prevent-abbreviations": ["warn", {
    replacements: {
      args: false,
      ctx: false,
      req: false,
      res: false
    }
  }],
  "string-content": "off",
  "throw-new-error": "warn"
})
